openapi: 3.0.1
info:
  title: Get_Local_Entry_Array_Data_API
  description: API Definition of Get_Local_Entry_Array_Data_API
  version: 1.0.0
servers:
- url: http://localhost:8290/Arraydata
paths:
  /:
    get:
      responses:
        default:
          description: Default response
