openapi: 3.0.1
info:
  title: Overeide_api
  description: API Definition of Overeide_api
  version: 1.0.0
servers:
- url: http://localhost:8290/Override
paths:
  /:
    get:
      responses:
        default:
          description: Default response
