openapi: 3.0.1
info:
  title: CsvtoJson_api
  description: API Definition of CsvtoJson_api
  version: 1.0.0
servers:
- url: http://localhost:8290/csvtojson
paths:
  /:
    post:
      responses:
        default:
          description: Default response
