openapi: 3.0.1
info:
  title: CONTRACT_CREATE_API
  description: API Definition of sample
  version: 1.0.0
servers:
- url: http://localhost:8290/contarctcreateapi
paths:
  /:
    post:
      responses:
        default:
          description: Default response
