openapi: 3.0.1
info:
  title: getperhost_API
  description: API Definition of getperhost_API
  version: 1.0.0
servers:
- url: http://localhost:8290/getperhost
paths:
  /:
    get:
      responses:
        default:
          description: Default response
