openapi: 3.0.1
info:
  title: dynamic_api
  description: API Definition of dynamic_api
  version: 1.0.0
servers:
- url: http://localhost:8290/dy
paths:
  /:
    get:
      responses:
        default:
          description: Default response
