openapi: 3.0.1
info:
  title: jyothi_api
  description: API Definition of jyothi_api
  version: 1.0.0
servers:
- url: http://localhost:8290/jyothi
paths:
  /jyo:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
