openapi: 3.0.1
info:
  title: Payload_freemaker-api
  description: API Definition of Payload_freemaker-api
  version: 1.0.0
servers:
- url: http://localhost:8290/payload
paths:
  /:
    post:
      responses:
        default:
          description: Default response
