openapi: 3.0.1
info:
  title: ReadCsvAsJson_API
  description: API Definition of ReadCsvAsJson_API
  version: 1.0.0
servers:
- url: http://localhost:8290/readcsvasjson
paths:
  /:
    get:
      responses:
        default:
          description: Default response
