openapi: 3.0.1
info:
  title: ReadCsvAsJson_Iterator_To_Another_API
  description: API Definition of ReadCsvAsJson_Iterator_To_Another_API
  version: 1.0.0
servers:
- url: http://localhost:8290/readcsvasjsontoanothercall
paths:
  /:
    get:
      responses:
        default:
          description: Default response
