openapi: 3.0.1
info:
  title: XMLasJson_API
  description: API Definition of XMLasJson_API
  version: 1.0.0
servers:
- url: http://localhost:8290/xmlasjson
paths:
  /:
    get:
      responses:
        default:
          description: Default response
