openapi: 3.0.1
info:
  title: FileConnectorAllMeditors_API
  description: API Definition of FileConnectorAllMeditors_API
  version: 1.0.0
servers:
- url: http://localhost:8290/AllMediators
paths:
  /:
    get:
      responses:
        default:
          description: Default response
