openapi: 3.0.1
info:
  title: storefiletrackdata
  description: API Definition of storefiletrackdata
  version: 1.0.0
servers:
- url: http://localhost:8290/storefiletrackdata
paths:
  /:
    get:
      responses:
        default:
          description: Default response
