openapi: 3.0.1
info:
  title: TrpExample
  description: API Definition of TrpExample
  version: 1.0.0
servers:
- url: http://localhost:8290/trpexample
paths:
  /:
    get:
      responses:
        default:
          description: Default response
