openapi: 3.0.1
info:
  title: Cachemediator_API
  description: API Definition of Cachemediator_API
  version: 1.0.0
servers:
- url: http://localhost:8290/cache
paths:
  /:
    post:
      responses:
        default:
          description: Default response
