openapi: 3.0.1
info:
  title: Java_code_for_Dynamic_query
  description: API Definition of Java_code_for_Dynamic_query
  version: 1.0.0
servers:
- url: http://localhost:8290/javacode
paths:
  /:
    get:
      responses:
        default:
          description: Default response
