openapi: 3.0.1
info:
  title: contract_write_api
  description: API Definition of contract_write_api
  version: 1.0.0
servers:
- url: http://localhost:8290/contract
paths:
  /:
    get:
      responses:
        default:
          description: Default response
