openapi: 3.0.1
info:
  title: jyothi_vyshu_fileread.xml
  description: API Definition of jyothi_vyshu_fileread
  version: 1.0.0
servers:
- url: http://localhost:8290/jyothivyshu
paths:
  /:
    get:
      responses:
        default:
          description: Default response
