openapi: 3.0.1
info:
  title: XmlAsCsv
  description: API Definition of XmlAsCsv
  version: 1.0.0
servers:
- url: http://localhost:8290/xmlascsv
paths:
  /:
    get:
      responses:
        default:
          description: Default response
