openapi: 3.0.1
info:
  title: DB_AJAY
  description: API Definition of DB_AJAY
  version: 1.0.0
servers:
- url: http://localhost:8290/dbajay
paths:
  /:
    get:
      responses:
        default:
          description: Default response
