openapi: 3.0.1
info:
  title: localentry
  description: API Definition of localentry
  version: 1.0.0
servers:
- url: http://localhost:8290/localentry
paths:
  /:
    get:
      responses:
        default:
          description: Default response
