openapi: 3.0.1
info:
  title: Cache_Per_Mediator_API
  description: API Definition of Cache_Per_Mediator_API
  version: 1.0.0
servers:
- url: http://localhost:8290/cachepermediator
paths:
  /:
    get:
      responses:
        default:
          description: Default response
