openapi: 3.0.1
info:
  title: CloneAndAggregrateBasedOnCondition
  description: API Definition of CloneAndAggregrateBasedOnCondition
  version: 1.0.0
servers:
- url: http://localhost:8290/cloneandaggregrate
paths:
  /:
    get:
      responses:
        default:
          description: Default response
